### PR TITLE
Update automoli.py

### PR DESCRIPTION
**Pull request by Allthebester**
Fix for AppDaemon 4.2.0, update "entity" to "entity_id" for "set_state" and "listen_state"

### CODE REVIEW

**Comment by ALutz273** [comment]
This commit works fine!

**Review by FredericESH — COMMENTED** [review]
works fine

**Review by FredericESH — APPROVED** [review]
works fine now

**Comment by legovaer** [comment]
Thanks a lot for this! As I only started using this app after the 4.2.0 release, I started to think that I was going mental. I've spent hours on reading the documentation and ended up on modifying the entire script.

Life saver!

**Comment by gogui63** [comment]
@benleb Could you merge this PR ?

**Comment by benleb** [comment]
sorry, give me a few hours 😄✌️

**Comment by gogui63** [comment]
@benleb Don't forget to make a new release when you have 5 minutes to get update on HACS side 😃 
And thanks again for this HA plugin !

**Comment by benleb** [comment]
tomorrow! 👍

**Comment by thundergreen** [comment]
WOW! thanks I was really confused that my lights would randomly turn on and off after Appdaemon update :P Now I know the answer. Thanks a thousand times!

**Pull request merged**
