### PR TITLE
Add only_own_events option to disable automoli if a light is switched…

### PR DESCRIPTION
**Pull request by chbndrhnns**
… on outside of automoli

This would be my attempt on https://github.com/benleb/ad-automoli/issues/39.

### CODE REVIEW

**Comment by chbndrhnns** [comment]
Actually, that's not working as expected. I will investigate further.

**Comment by benleb** [comment]
Okay, ping me if you are ready 👍

**Comment by benleb** [comment]
hey, I looked over this today and if I understand it correctly, that should already work... is this is what you want?

- Lights are off
- Manual switching on
- AutoMoLi **will not** (ok, should not :D) switch off the lights or change them

:)

**Comment by chbndrhnns** [comment]
With these changes, it works for me like this: if automoli did not switch ON a light, it will also not switch it off. I was not able to test with special behavior for Hue groups, for example.

**Comment by benleb** [comment]
Okay, I will also test a little before merge :) If anyone else tests this and experience same issues, please comment :)

Thank you @chbndrhnns !

**Pull request merged**
